version: 2
jobs: 
  build: 
    docker:
      - image: circleci/node:8.9.4
    environment:
      # from https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_standalone.htm
      # and https://developer.salesforce.com/media/salesforce-cli/manifest.json

      # Variables used in build steps
      - DX_CLI_URL: https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
      - TESTLEVEL: RunLocalTests
      - DEPLOYDIR: src
    steps:
      - checkout
      - run:
          name: "Create SFDX Folder" 
          command: |
            # Create sfdx directory
            mkdir sfdx
      - run:
          name: Download CLI
          command: |
            # Download cli
            wget -qO- $DX_CLI_URL | tar xJ -C sfdx --strip-components 1
      - run:
          name: Install CLI
          command: |
            # Install the cli
            ./sfdx/install
            sfdx
      - run:
            name: Decrypt server key
            command: |
              #Decrypt server key
              sfdx force --help
      - run:
            name: auth 
            command: |
              #Decrypt server key
              sfdx-circleci-org> sfdx force:auth:sfdxurl:store -f assets/sfdxurl.txt -d -a hub-sfdx-circleci-org